export const topics = [
    {
        id: "1",
        category: "OVERCROWDING",
        title: "Access to Bail: Challenges for the Undertrial Prisoners",
        org: "Prison Reform Initiative",
        orgInitial: "P",
        date: "2025-08-23",
        imageUrl: "/Overcrowding2.png",
        tags: ["Policy", "Bail"],
        type: "Video" as const,
    },
    {
        id: "2",
        category: "OVERCROWDING",
        title: "Overcrowding in Indian Prisons: A National Concern",
        org: "Human Rights Commission",
        orgInitial: "H",
        date: "2025-08-23",
        imageUrl: "/Rules2.png",
        tags: ["Report", "National"],
        type: "Report" as const,
    },
    {
        id: "3",
        category: "OVERCROWDING",
        title: "Legal Aid Behind Bars: Bridging the Persistent Justice Gap",
        org: "Prison Reform Initiative",
        orgInitial: "P",
        date: "2025-08-23",
        imageUrl: "/Featured.png",
        tags: ["Justice", "Legal Aid"],
        type: "Podcast" as const,
    },
    {
        id: "4",
        category: "OVERCROWDING",
        title: "Nutrition and Health: Daily Realities of Inmates Worldwide",
        org: "Supreme court of India",
        orgInitial: "S",
        date: "2025-08-23",
        imageUrl: "/Podcast2.jpg",
        tags: ["Health", "Nutrition"],
        type: "Judgement" as const,
    },
    {
        id: "5",
        category: "OVERCROWDING",
        title: "Legal Aid Behind Bars: Bridging the Persistent Justice Gap",
        org: "Prison Reform Initiative",
        orgInitial: "P",
        date: "2025-08-23",
        imageUrl: "/Featured.png",
        tags: ["Justice", "Legal Aid"],
        type: "Podcast" as const,
    },
     {
        id: "6",
        category: "OVERCROWDING",
        title: "Access to Bail: Challenges for the Undertrial Prisoners",
        org: "Prison Reform Initiative",
        orgInitial: "P",
        date: "2025-08-23",
        imageUrl: "/Overcrowding2.png",
        tags: ["Policy", "Bail"],
        type: "Video" as const,
    },
]